// Package products provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package products

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	ClientContextScopes = "ClientContext.Scopes"
)

// Defines values for ProductsProductItemInventoryModelStockLevel.
const (
	HIGH                  ProductsProductItemInventoryModelStockLevel = "HIGH"
	LOW                   ProductsProductItemInventoryModelStockLevel = "LOW"
	TEMPORARILYOUTOFSTOCK ProductsProductItemInventoryModelStockLevel = "TEMPORARILY_OUT_OF_STOCK"
)

// Valid indicates whether the value is a known member of the ProductsProductItemInventoryModelStockLevel enum.
func (e ProductsProductItemInventoryModelStockLevel) Valid() bool {
	switch e {
	case HIGH:
		return true
	case LOW:
		return true
	case TEMPORARILYOUTOFSTOCK:
		return true
	default:
		return false
	}
}

// Defines values for ProductGetParamsFilterFulfillment.
const (
	Ais ProductGetParamsFilterFulfillment = "ais"
	Csp ProductGetParamsFilterFulfillment = "csp"
	Dth ProductGetParamsFilterFulfillment = "dth"
	Sth ProductGetParamsFilterFulfillment = "sth"
)

// Valid indicates whether the value is a known member of the ProductGetParamsFilterFulfillment enum.
func (e ProductGetParamsFilterFulfillment) Valid() bool {
	switch e {
	case Ais:
		return true
	case Csp:
		return true
	case Dth:
		return true
	case Sth:
		return true
	default:
		return false
	}
}

// APIError defines model for APIError.
type APIError struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// APIErrorForbidden defines model for APIError.forbidden.
type APIErrorForbidden struct {
	Errors *struct {
		Code      *string  `json:"code,omitempty"`
		Reason    *string  `json:"reason,omitempty"`
		Timestamp *float32 `json:"timestamp,omitempty"`
	} `json:"errors,omitempty"`
}

// APIErrorProductsServerError defines model for APIError.products.serverError.
type APIErrorProductsServerError struct {
	Errors *struct {
		Code      *string  `json:"code,omitempty"`
		Reason    *string  `json:"reason,omitempty"`
		Timestamp *float32 `json:"timestamp,omitempty"`
	} `json:"errors,omitempty"`
}

// APIErrorUnauthorized defines model for APIError.unauthorized.
type APIErrorUnauthorized struct {
	Errors *struct {
		Error            *string `json:"error,omitempty"`
		ErrorDescription *string `json:"error_description,omitempty"`
	} `json:"errors,omitempty"`
}

// InvalidUPC defines model for Invalid_UPC.
type InvalidUPC struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// InvalidLimit defines model for Invalid_limit.
type InvalidLimit struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// InvalidLocationId defines model for Invalid_locationId.
type InvalidLocationId struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// InvalidParameter defines model for Invalid_parameter.
type InvalidParameter struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// UPC The UPC of the product to return.
type UPC = string

// ProductId The productId of the product to return.
type ProductId = string

// ProductsAllergenModel defines model for products.allergenModel.
type ProductsAllergenModel struct {
	LevelOfContainmentName *string `json:"levelOfContainmentName,omitempty"`
	Name                   *string `json:"name,omitempty"`
}

// ProductsProductAisleLocationModel defines model for products.productAisleLocationModel.
type ProductsProductAisleLocationModel struct {
	// BayNumber The bay number of the aisle.
	BayNumber *string `json:"bayNumber,omitempty"`

	// Description The location in the store.
	Description *string `json:"description,omitempty"`

	// Number The aisle number in the store.
	Number *string `json:"number,omitempty"`

	// NumberOfFacings The number of facings.
	NumberOfFacings *string `json:"numberOfFacings,omitempty"`

	// SequenceNumber The sequence of the aisle in the store.
	SequenceNumber *string `json:"sequenceNumber,omitempty"`

	// ShelfNumber The shelf number in the aisle.
	ShelfNumber *string `json:"shelfNumber,omitempty"`

	// ShelfPositionInBay The position of the shelf in the bay.
	ShelfPositionInBay *string `json:"shelfPositionInBay,omitempty"`

	// Side The side of the aisle where the product is located.
	Side *string `json:"side,omitempty"`
}

// ProductsProductBoxedDimensionsModel Information about the product's size.
type ProductsProductBoxedDimensionsModel struct {
	// AverageWeightPerUnit The average weight per unit of the product.
	AverageWeightPerUnit *string `json:"averageWeightPerUnit,omitempty"`

	// Depth The depth of the product.
	Depth *string `json:"depth,omitempty"`

	// GrossWeight The gross weight of the product.
	GrossWeight *string `json:"grossWeight,omitempty"`

	// Height The height of the product.
	Height *string `json:"height,omitempty"`

	// NetWeight The net weight of the product.
	NetWeight *string `json:"netWeight,omitempty"`

	// Width The length of the product.
	Width *string `json:"width,omitempty"`
}

// ProductsProductImageModel Information about the product's image.
type ProductsProductImageModel struct {
	Default *bool `json:"default,omitempty"`

	// Id An optional identifier of the image size.
	Id *string `json:"id,omitempty"`

	// Perspective A description of the product image view.
	Perspective *string `json:"perspective,omitempty"`

	// Sizes An array of image sizes.
	Sizes *[]ProductsProductImageSizeModel `json:"sizes,omitempty"`
}

// ProductsProductImageSizeModel Information about the product's image.
type ProductsProductImageSizeModel struct {
	// Id An optional identifier of the image size.
	Id *string `json:"id,omitempty"`

	// Size A description of the image size.
	Size *string `json:"size,omitempty"`

	// Url The URL location of the image.
	Url *string `json:"url,omitempty"`
}

// ProductsProductItemFulfillmentModel defines model for products.productItemFulfillmentModel.
type ProductsProductItemFulfillmentModel struct {
	// Curbside Indicates if the product is available for curbside pickup.
	Curbside *bool `json:"curbside,omitempty"`

	// Delivery Indicates if the product is available for home delivery.
	Delivery *bool `json:"delivery,omitempty"`

	// Instore Indicates if the product is available in store. This does not indicate that the item is in stock.
	Instore *bool `json:"instore,omitempty"`

	// Shiptohome Indicates if the product is available to be shipped from a fulfillment center.
	Shiptohome *bool `json:"shiptohome,omitempty"`
}

// ProductsProductItemInventoryModel defines model for products.productItemInventoryModel.
type ProductsProductItemInventoryModel struct {
	// StockLevel Indicates the level of stock.
	StockLevel *ProductsProductItemInventoryModelStockLevel `json:"stockLevel,omitempty"`
}

// ProductsProductItemInventoryModelStockLevel Indicates the level of stock.
type ProductsProductItemInventoryModelStockLevel string

// ProductsProductItemModel defines model for products.productItemModel.
type ProductsProductItemModel struct {
	Favorite    *bool                                `json:"favorite,omitempty"`
	Fulfillment *ProductsProductItemFulfillmentModel `json:"fulfillment,omitempty"`
	Inventory   *ProductsProductItemInventoryModel   `json:"inventory,omitempty"`

	// ItemId The UPC of the item.
	ItemId        *string                        `json:"itemId,omitempty"`
	NationalPrice *ProductsProductItemPriceModel `json:"nationalPrice,omitempty"`
	Price         *ProductsProductItemPriceModel `json:"price,omitempty"`

	// Size A description of the item size.
	Size *string `json:"size,omitempty"`

	// SoldBy Indicates how this item is sold. Values returned are typically either "weight" or "unit"
	SoldBy *string `json:"soldBy,omitempty"`
}

// ProductsProductItemPriceModel defines model for products.productItemPriceModel.
type ProductsProductItemPriceModel struct {
	// Promo The sale price of the item.
	Promo *float32 `json:"promo,omitempty"`

	// PromoPerUnitEstimate The estimated sale price of 1 unit of the item.
	PromoPerUnitEstimate *float32 `json:"promoPerUnitEstimate,omitempty"`

	// Regular The regular price of the item.
	Regular *float32 `json:"regular,omitempty"`

	// RegularPerUnitEstimate The estimated price of 1 unit of the item.
	RegularPerUnitEstimate *float32 `json:"regularPerUnitEstimate,omitempty"`
}

// ProductsProductModel defines model for products.productModel.
type ProductsProductModel struct {
	// AgeRestriction Indicates if the product has an age restriction.
	AgeRestriction *bool                                `json:"ageRestriction,omitempty"`
	AisleLocations *[]ProductsProductAisleLocationModel `json:"aisleLocations,omitempty"`

	// Alcohol Indicates if the product contains alcohol.
	Alcohol *bool `json:"alcohol,omitempty"`

	// AlcoholProof The proof of the alcohol in the product.
	AlcoholProof *int `json:"alcoholProof,omitempty"`

	// AliasProductIds The alias ProductId of the product to return.
	AliasProductIds *[]string                `json:"aliasProductIds,omitempty"`
	Allergens       *[]ProductsAllergenModel `json:"allergens,omitempty"`

	// AllergensDescription The description of the allergens for the product.
	AllergensDescription *string `json:"allergensDescription,omitempty"`

	// Brand The brand name of the product.
	Brand *string `json:"brand,omitempty"`

	// Categories The category the product belongs to.
	Categories *[]string `json:"categories,omitempty"`

	// CertifiedForPassover Indicates if the product is certified for Passover.
	CertifiedForPassover *bool `json:"certifiedForPassover,omitempty"`

	// CountryOrigin The country of origin of the product.
	CountryOrigin *string `json:"countryOrigin,omitempty"`

	// Description The name of the product.
	Description *string `json:"description,omitempty"`

	// Hypoallergenic Indicates if the product is hypoallergenic.
	Hypoallergenic *bool                        `json:"hypoallergenic,omitempty"`
	Images         *[]ProductsProductImageModel `json:"images,omitempty"`

	// ItemInformation Information about the product's size.
	ItemInformation *ProductsProductBoxedDimensionsModel `json:"itemInformation,omitempty"`
	Items           *[]ProductsProductItemModel          `json:"items,omitempty"`

	// ManufacturerDeclarations Any manufacturer declarations for the product.
	ManufacturerDeclarations *[]string `json:"manufacturerDeclarations,omitempty"`

	// NonGmo Indicates if the product is non-GMO.
	NonGmo *bool `json:"nonGmo,omitempty"`

	// NonGmoClaimName The name of the non-GMO claim.
	NonGmoClaimName *string `json:"nonGmoClaimName,omitempty"`

	// OrganicClaimName The name of the organic claim.
	OrganicClaimName *string `json:"organicClaimName,omitempty"`

	// ProductId The UPC of the product.
	ProductId *string `json:"productId,omitempty"`

	// ProductPageURI The URI of the product page.
	ProductPageURI    *string `json:"productPageURI,omitempty"`
	RatingsAndReviews *struct {
		// AverageOverallRating The average overall rating of the product.
		AverageOverallRating *float32 `json:"averageOverallRating,omitempty"`

		// TotalReviewCount The total number of reviews for the product.
		TotalReviewCount *int `json:"totalReviewCount,omitempty"`
	} `json:"ratingsAndReviews,omitempty"`

	// ReceiptDescription The description of the product to appear on the receipt.
	ReceiptDescription *string                    `json:"receiptDescription,omitempty"`
	Retstrictions      *ProductsRestrictionsModel `json:"retstrictions,omitempty"`

	// SnapEligible Indicates if the product is eligible for SNAP benefits.
	SnapEligible      *bool `json:"snapEligible,omitempty"`
	SweeteningMethods *struct {
		Code *string `json:"code,omitempty"`
		Name *string `json:"name,omitempty"`
	} `json:"sweeteningMethods,omitempty"`

	// Temperature Information about the item's temperature requirements.
	Temperature *ProductsProductTemperatureModel `json:"temperature,omitempty"`

	// Upc The UPC of the product.
	Upc *string `json:"upc,omitempty"`

	// Warnings Any warnings for the product.
	Warnings *string `json:"warnings,omitempty"`
}

// ProductsProductPayloadModel defines model for products.productPayloadModel.
type ProductsProductPayloadModel struct {
	Data *ProductsProductModel   `json:"data,omitempty"`
	Meta *map[string]interface{} `json:"meta,omitempty"`
}

// ProductsProductTemperatureModel Information about the item's temperature requirements.
type ProductsProductTemperatureModel struct {
	// HeatSensitive Indicates if the item is heat sensitive.
	HeatSensitive *bool `json:"heatSensitive,omitempty"`

	// Indicator Information about the product's storage temperature.
	Indicator *string `json:"indicator,omitempty"`
}

// ProductsProductsPayloadModel defines model for products.productsPayloadModel.
type ProductsProductsPayloadModel struct {
	Data *[]ProductsProductModel `json:"data,omitempty"`
	Meta *map[string]interface{} `json:"meta,omitempty"`
}

// ProductsRestrictionsModel defines model for products.restrictionsModel.
type ProductsRestrictionsModel struct {
	MaximumOrderQuantity *int      `json:"maximumOrderQuantity,omitempty"`
	MinimumOrderQuantity *int      `json:"minimumOrderQuantity,omitempty"`
	PostalCode           *[]string `json:"postalCode,omitempty"`
	Shippable            *bool     `json:"shippable,omitempty"`
	StateCodes           *[]string `json:"stateCodes,omitempty"`
}

// ProductGetParams defines parameters for ProductGet.
type ProductGetParams struct {
	// FilterTerm A search term to filter product results. As an example, you could input _milk_, _bread_, or _salt_. <br><br><b>Note</b> - Search terms are limited to a maximum of 8 words. Each new space in the search term denotes a new word.
	FilterTerm *string `form:"filter.term,omitempty" json:"filter.term,omitempty"`

	// FilterLocationId The locationId of the location. When using this filter, only products available at that location are returned.
	FilterLocationId *string `form:"filter.locationId,omitempty" json:"filter.locationId,omitempty"`

	// FilterProductId The productId of the products(s) to return. For more than one item, the list must be comma-separated. When used, all other query parameters are ignored.
	FilterProductId *string `form:"filter.productId,omitempty" json:"filter.productId,omitempty"`

	// FilterBrand The brand name of the products to return. When using this filter, only products by that brand are returned. Brand names are case-sensitive, and lists must be pipe-separated.
	FilterBrand *string `form:"filter.brand,omitempty" json:"filter.brand,omitempty"`

	// FilterFulfillment 'The available fulfillment types of the product(s) to return.
	// Fulfillment types are case-sensitive, and lists must be comma-separated.
	// Must be one or more of the follow types: <ul> <li> `ais` - Available In
	// Store</li> <li> `csp` - Curbside Pickup</li> <li> `dth` - Delivery To Home</li>
	// <li> `sth` - Ship To Home</li> </ui>'
	FilterFulfillment *ProductGetParamsFilterFulfillment `form:"filter.fulfillment,omitempty" json:"filter.fulfillment,omitempty"`

	// FilterStart The number of products to skip.
	FilterStart *int `form:"filter.start,omitempty" json:"filter.start,omitempty"`

	// FilterLimit The number of products to return.
	FilterLimit *int `form:"filter.limit,omitempty" json:"filter.limit,omitempty"`
}

// ProductGetParamsFilterFulfillment defines parameters for ProductGet.
type ProductGetParamsFilterFulfillment string

// ProductGetIDParams defines parameters for ProductGetID.
type ProductGetIDParams struct {
	// FilterLocationId The locationId of the location. When using this filter, only products available at that location are returned.
	FilterLocationId *string `form:"filter.locationId,omitempty" json:"filter.locationId,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ProductGet request
	ProductGet(ctx context.Context, params *ProductGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProductGetID request
	ProductGetID(ctx context.Context, id struct {
		union json.RawMessage
	}, params *ProductGetIDParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ProductGet(ctx context.Context, params *ProductGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProductGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProductGetID(ctx context.Context, id struct {
	union json.RawMessage
}, params *ProductGetIDParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProductGetIDRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewProductGetRequest generates requests for ProductGet
func NewProductGetRequest(server string, params *ProductGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/products")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.FilterTerm != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.term", *params.FilterTerm, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterLocationId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.locationId", *params.FilterLocationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterProductId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.productId", *params.FilterProductId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterBrand != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.brand", *params.FilterBrand, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterFulfillment != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.fulfillment", *params.FilterFulfillment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterStart != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.start", *params.FilterStart, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterLimit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.limit", *params.FilterLimit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProductGetIDRequest generates requests for ProductGetID
func NewProductGetIDRequest(server string, id struct {
	union json.RawMessage
}, params *ProductGetIDParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/products/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.FilterLocationId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.locationId", *params.FilterLocationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ProductGetWithResponse request
	ProductGetWithResponse(ctx context.Context, params *ProductGetParams, reqEditors ...RequestEditorFn) (*ProductGetResponse, error)

	// ProductGetIDWithResponse request
	ProductGetIDWithResponse(ctx context.Context, id struct {
		union json.RawMessage
	}, params *ProductGetIDParams, reqEditors ...RequestEditorFn) (*ProductGetIDResponse, error)
}

type ProductGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProductsProductsPayloadModel
	JSON400      *struct {
		union json.RawMessage
	}
	JSON401 *APIErrorUnauthorized
	JSON403 *APIErrorForbidden
	JSON500 *APIErrorProductsServerError
}

// Status returns HTTPResponse.Status
func (r ProductGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProductGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ProductGetIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProductsProductPayloadModel
	JSON400      *struct {
		union json.RawMessage
	}
	JSON401 *APIErrorUnauthorized
	JSON403 *APIErrorForbidden
	JSON500 *APIErrorProductsServerError
}

// Status returns HTTPResponse.Status
func (r ProductGetIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProductGetIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ProductGetWithResponse request returning *ProductGetResponse
func (c *ClientWithResponses) ProductGetWithResponse(ctx context.Context, params *ProductGetParams, reqEditors ...RequestEditorFn) (*ProductGetResponse, error) {
	rsp, err := c.ProductGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProductGetResponse(rsp)
}

// ProductGetIDWithResponse request returning *ProductGetIDResponse
func (c *ClientWithResponses) ProductGetIDWithResponse(ctx context.Context, id struct {
	union json.RawMessage
}, params *ProductGetIDParams, reqEditors ...RequestEditorFn) (*ProductGetIDResponse, error) {
	rsp, err := c.ProductGetID(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProductGetIDResponse(rsp)
}

// ParseProductGetResponse parses an HTTP response from a ProductGetWithResponse call
func ParseProductGetResponse(rsp *http.Response) (*ProductGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProductGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProductsProductsPayloadModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest APIErrorUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIErrorForbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest APIErrorProductsServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseProductGetIDResponse parses an HTTP response from a ProductGetIDWithResponse call
func ParseProductGetIDResponse(rsp *http.Response) (*ProductGetIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProductGetIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProductsProductPayloadModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest APIErrorUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest APIErrorForbidden
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest APIErrorProductsServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
