// Package locations provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package locations

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	ClientContextScopes = "ClientContext.Scopes"
)

// APIError defines model for APIError.
type APIError struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// APIErrorLocationsServerError defines model for APIError.locations.serverError.
type APIErrorLocationsServerError struct {
	Errors *struct {
		Code      *string  `json:"code,omitempty"`
		Reason    *string  `json:"reason,omitempty"`
		Timestamp *float32 `json:"timestamp,omitempty"`
	} `json:"errors,omitempty"`
}

// APIErrorNotFound defines model for APIError.notFound.
type APIErrorNotFound = map[string]interface{}

// APIErrorUnauthorized defines model for APIError.unauthorized.
type APIErrorUnauthorized struct {
	Errors *struct {
		Error            *string `json:"error,omitempty"`
		ErrorDescription *string `json:"error_description,omitempty"`
	} `json:"errors,omitempty"`
}

// InvalidDepartment defines model for Invalid_department.
type InvalidDepartment struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// InvalidLatLong defines model for Invalid_latLong.
type InvalidLatLong struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// InvalidLimit defines model for Invalid_limit.
type InvalidLimit struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// InvalidLocationId defines model for Invalid_locationId.
type InvalidLocationId struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// InvalidRadiusInMiles defines model for Invalid_radiusInMiles.
type InvalidRadiusInMiles struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// InvalidZipCode defines model for Invalid_zipCode.
type InvalidZipCode struct {
	Code      *string  `json:"code,omitempty"`
	Reason    *string  `json:"reason,omitempty"`
	Timestamp *float32 `json:"timestamp,omitempty"`
}

// MetaModel defines model for MetaModel.
type MetaModel struct {
	Pagination *struct {
		Limit *float32 `json:"limit,omitempty"`
		Start *float32 `json:"start,omitempty"`
		Total *float32 `json:"total,omitempty"`
	} `json:"pagination,omitempty"`
	Warnings *[]string `json:"warnings,omitempty"`
}

// LocationsAddress defines model for locations.address.
type LocationsAddress struct {
	// AddressLine1 The street address of the location.
	AddressLine1 *string `json:"addressLine1,omitempty"`

	// AddressLine2 An optional secondary address of the location.
	AddressLine2 *string `json:"addressLine2,omitempty"`

	// City The city of the location.
	City *string `json:"city,omitempty"`

	// County The county of the location.
	County *string `json:"county,omitempty"`

	// State The state or province of the location. US locations use a two-letter codes for states.
	State *string `json:"state,omitempty"`

	// ZipCode The postal code of the location.
	ZipCode *string `json:"zipCode,omitempty"`
}

// LocationsDailyHours defines model for locations.dailyHours.
type LocationsDailyHours struct {
	// Close The time the department or location closes.
	Close *string `json:"close,omitempty"`

	// Open The time the department or location opens.
	Open *string `json:"open,omitempty"`

	// Open24 Indicates if the location or department is open 24 hours.
	Open24 *bool `json:"open24,omitempty"`
}

// LocationsDepartmentAtLocation defines model for locations.departmentAtLocation.
type LocationsDepartmentAtLocation struct {
	// DepartmentId The 2-digit department code.
	DepartmentId *string                   `json:"departmentId,omitempty"`
	Hours        *LocationsDepartmentHours `json:"hours,omitempty"`

	// Name The name of the department.
	Name *string `json:"name,omitempty"`

	// Phone The phone number of the department.
	Phone *string `json:"phone,omitempty"`
}

// LocationsDepartmentHours defines model for locations.departmentHours.
type LocationsDepartmentHours struct {
	// Open24 Indicates if the location is open 24 hours.
	Open24    *bool                `json:"Open24,omitempty"`
	Friday    *LocationsDailyHours `json:"friday,omitempty"`
	Monday    *LocationsDailyHours `json:"monday,omitempty"`
	Saturday  *LocationsDailyHours `json:"saturday,omitempty"`
	Sunday    *LocationsDailyHours `json:"sunday,omitempty"`
	Thursday  *LocationsDailyHours `json:"thursday,omitempty"`
	Tuesday   *LocationsDailyHours `json:"tuesday,omitempty"`
	Wednesday *LocationsDailyHours `json:"wednesday,omitempty"`
}

// LocationsGeoLocation defines model for locations.geoLocation.
type LocationsGeoLocation struct {
	// LatLng The latitude and longitude of the location, comma separated
	LatLng *string `json:"latLng,omitempty"`

	// Latitude The latitude of the location
	Latitude *float32 `json:"latitude,omitempty"`

	// Longitude The longitude of the location
	Longitude *float32 `json:"longitude,omitempty"`
}

// LocationsLocation defines model for locations.location.
type LocationsLocation struct {
	Address *LocationsAddress `json:"address,omitempty"`

	// Chain The name of the chain.
	Chain *string `json:"chain,omitempty"`

	// Departments The available departments at the location.
	Departments *[]LocationsDepartmentAtLocation `json:"departments,omitempty"`

	// DivisionNumber The 3-digit management division number.
	DivisionNumber *string                 `json:"divisionNumber,omitempty"`
	Geolocation    *LocationsGeoLocation   `json:"geolocation,omitempty"`
	Hours          *LocationsLocationHours `json:"hours,omitempty"`

	// LocationId The 3-digit management division number followed by the 5-digit store number.
	LocationId *string `json:"locationId,omitempty"`

	// Name The name of the location. The name generally consists of the chain followed by a vanity name.
	Name *string `json:"name,omitempty"`

	// Phone The phone number of the location.
	Phone *string `json:"phone,omitempty"`

	// StoreNumber The 5-digit store number.
	StoreNumber *string `json:"storeNumber,omitempty"`
}

// LocationsLocationHours defines model for locations.locationHours.
type LocationsLocationHours struct {
	// Open24 Indicates if the location is open 24 hours.
	Open24 *bool                `json:"Open24,omitempty"`
	Friday *LocationsDailyHours `json:"friday,omitempty"`

	// GmtOffset The utc timezone offset from gmt.
	GmtOffset *string              `json:"gmtOffset,omitempty"`
	Monday    *LocationsDailyHours `json:"monday,omitempty"`
	Saturday  *LocationsDailyHours `json:"saturday,omitempty"`
	Sunday    *LocationsDailyHours `json:"sunday,omitempty"`
	Thursday  *LocationsDailyHours `json:"thursday,omitempty"`

	// Timezone The timezone of the location.
	Timezone  *string              `json:"timezone,omitempty"`
	Tuesday   *LocationsDailyHours `json:"tuesday,omitempty"`
	Wednesday *LocationsDailyHours `json:"wednesday,omitempty"`
}

// LocationsLocationResponse defines model for locations.locationResponse.
type LocationsLocationResponse struct {
	Data *LocationsLocation `json:"data,omitempty"`
	Meta *MetaModel         `json:"meta,omitempty"`
}

// LocationsLocationSearchResponse defines model for locations.locationSearchResponse.
type LocationsLocationSearchResponse struct {
	Data *[]LocationsLocation `json:"data,omitempty"`
	Meta *MetaModel           `json:"meta,omitempty"`
}

// SearchLocationsParams defines parameters for SearchLocations.
type SearchLocationsParams struct {
	// FilterZipCodeNear The zip code to use as a starting point for results.
	FilterZipCodeNear *string `form:"filter.zipCode.near,omitempty" json:"filter.zipCode.near,omitempty"`

	// FilterLatLongNear The latitude and longitude to use as a starting point for results.
	FilterLatLongNear *string `form:"filter.latLong.near,omitempty" json:"filter.latLong.near,omitempty"`

	// FilterLatNear The latitude to use as a starting point for results.
	FilterLatNear *string `form:"filter.lat.near,omitempty" json:"filter.lat.near,omitempty"`

	// FilterLonNear The longitude to use as a starting point for results.
	FilterLonNear *string `form:"filter.lon.near,omitempty" json:"filter.lon.near,omitempty"`

	// FilterRadiusInMiles The mile radius of results. This will be ignored if you do not use one of the 3 starting point filters (zipCode, latLong, or lat and lon)
	FilterRadiusInMiles *int `form:"filter.radiusInMiles,omitempty" json:"filter.radiusInMiles,omitempty"`

	// FilterLimit The number of results to return.
	FilterLimit *int `form:"filter.limit,omitempty" json:"filter.limit,omitempty"`

	// FilterChain The chain name of the chain. When using this filter, only stores matching the provided chain name are returned.
	FilterChain *string `form:"filter.chain,omitempty" json:"filter.chain,omitempty"`

	// FilterDepartment The departmentId of the department. Lists must be comma-separated. When using this filter, only stores that have all of the departments provided are returned.
	FilterDepartment *string `form:"filter.department,omitempty" json:"filter.department,omitempty"`

	// FilterLocationId Comma-separated list of locationIds.
	FilterLocationId *string `form:"filter.locationId,omitempty" json:"filter.locationId,omitempty"`
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// SearchLocations request
	SearchLocations(ctx context.Context, params *SearchLocationsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// LocationsGetByID request
	LocationsGetByID(ctx context.Context, locationId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) SearchLocations(ctx context.Context, params *SearchLocationsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchLocationsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) LocationsGetByID(ctx context.Context, locationId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewLocationsGetByIDRequest(c.Server, locationId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewSearchLocationsRequest generates requests for SearchLocations
func NewSearchLocationsRequest(server string, params *SearchLocationsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/locations")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.FilterZipCodeNear != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.zipCode.near", *params.FilterZipCodeNear, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterLatLongNear != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.latLong.near", *params.FilterLatLongNear, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterLatNear != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.lat.near", *params.FilterLatNear, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterLonNear != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.lon.near", *params.FilterLonNear, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterRadiusInMiles != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.radiusInMiles", *params.FilterRadiusInMiles, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterLimit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.limit", *params.FilterLimit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterChain != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.chain", *params.FilterChain, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterDepartment != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.department", *params.FilterDepartment, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.FilterLocationId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "filter.locationId", *params.FilterLocationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewLocationsGetByIDRequest generates requests for LocationsGetByID
func NewLocationsGetByIDRequest(server string, locationId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "locationId", locationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/locations/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// SearchLocationsWithResponse request
	SearchLocationsWithResponse(ctx context.Context, params *SearchLocationsParams, reqEditors ...RequestEditorFn) (*SearchLocationsResponse, error)

	// LocationsGetByIDWithResponse request
	LocationsGetByIDWithResponse(ctx context.Context, locationId string, reqEditors ...RequestEditorFn) (*LocationsGetByIDResponse, error)
}

type SearchLocationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LocationsLocationSearchResponse
	JSON400      *struct {
		union json.RawMessage
	}
	JSON401 *APIErrorUnauthorized
	JSON404 *APIErrorNotFound
	JSON500 *APIErrorLocationsServerError
}

// Status returns HTTPResponse.Status
func (r SearchLocationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchLocationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type LocationsGetByIDResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *LocationsLocationResponse
	JSON400      *struct {
		union json.RawMessage
	}
	JSON401 *APIErrorUnauthorized
	JSON404 *APIErrorNotFound
	JSON500 *APIErrorLocationsServerError
}

// Status returns HTTPResponse.Status
func (r LocationsGetByIDResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r LocationsGetByIDResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// SearchLocationsWithResponse request returning *SearchLocationsResponse
func (c *ClientWithResponses) SearchLocationsWithResponse(ctx context.Context, params *SearchLocationsParams, reqEditors ...RequestEditorFn) (*SearchLocationsResponse, error) {
	rsp, err := c.SearchLocations(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchLocationsResponse(rsp)
}

// LocationsGetByIDWithResponse request returning *LocationsGetByIDResponse
func (c *ClientWithResponses) LocationsGetByIDWithResponse(ctx context.Context, locationId string, reqEditors ...RequestEditorFn) (*LocationsGetByIDResponse, error) {
	rsp, err := c.LocationsGetByID(ctx, locationId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseLocationsGetByIDResponse(rsp)
}

// ParseSearchLocationsResponse parses an HTTP response from a SearchLocationsWithResponse call
func ParseSearchLocationsResponse(rsp *http.Response) (*SearchLocationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchLocationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LocationsLocationSearchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest APIErrorUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest APIErrorNotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest APIErrorLocationsServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParseLocationsGetByIDResponse parses an HTTP response from a LocationsGetByIDWithResponse call
func ParseLocationsGetByIDResponse(rsp *http.Response) (*LocationsGetByIDResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &LocationsGetByIDResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LocationsLocationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest struct {
			union json.RawMessage
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest APIErrorUnauthorized
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest APIErrorNotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest APIErrorLocationsServerError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}
