# .github/workflows/ghcr-publish.yml
name: Publish to GHCR

on:
  push:
    branches: ["main"]   # change if needed
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write      # required to push to GHCR with GITHUB_TOKEN

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Derive image name and tags
        id: vars
        run: |
          # Lowercase is safest for registry paths
          REPO_LC="$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')"
          echo "IMAGE=ghcr.io/${REPO_LC}" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=${GITHUB_SHA::12}" >> "$GITHUB_OUTPUT"

      - name: Login to GHCR (uses built-in GITHUB_TOKEN)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.vars.outputs.IMAGE }}:latest
            ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.SHORT_SHA }}
